### ISSUE TITLE
What is adopter_args?

### ISSUE THREAD

**Issue by azharmalik3** [KallDrexx/elixir-media-libs#18]
Could you please tell me about `adopter_args` and what arguments should i pass?

https://github.com/KallDrexx/elixir-media-libs/blob/master/apps/gen_rtmp_client/lib/gen_rtmp_client.ex#L59

**Comment by KallDrexx** [comment]
Wow, sorry I never saw this :(.  I didn't get an email notification for some reason.

`adopter_args` are just optional arguments that are passed straight through to the module you created that adopts the `GenRtmpClient` behaviour.  This allows you to pass any options that you want that are specific to your custom implementation, just like how `GenServer.start_link()`'s second parameter is passed straight to your module's `init()` function when creating a custom genserver.
